[package]
name = "example"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pros = { git = "https://github.com/pros-rs/pros-rs", branch = "async_runtime" }
# pros = { path = "../../pros-rs/pros" }
