[package]
name = "pros-simulator-interface"
description = "Connect your app to the pros-simulator crate."
version = "0.1.0"
edition = "2021"
license = "MIT"
authors = ["doinkythederp <doinkythederp@icloud.com>", "Pros-rs Contributors"]
repository = "https://github.com/pros-rs/pros-simulator"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0.193", features = ["derive"] }
