[package]
name = "pros-simulator-interface"
version = "0.1.0"
edition = "2021"
license = "MIT"
authors = ["doinkythederp <doinkythederp@icloud.com>", "Pros-rs Contributors"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0.193", features = ["derive"] }
