[workspace]
resolver = "2"
members = ["packages/*"]
exclude = ["packages/example"]

[profile.release-debuginfo]
inherits = "release"
debug = "limited"
strip = false

[profile.release]
lto = "thin"
strip = true
