[workspace]
resolver = "2"
members = ["packages/*"]

[profile.release-limited-debuginfo]
inherits = "release"
lto = "thin"
debug = "limited"

[profile.release-debuginfo]
inherits = "release"
lto = "thin"
debug = true
