[package]
name = "pros-simulator-server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.4.9", features = ["derive"] }
jsonl = "4.0.1"
pros-simulator = { version = "0.2.0", path = "../pros-simulator", default-features = false }
pros-simulator-interface = { version = "0.2.0", path = "../pros-simulator-interface" }
tokio = { version = "1.34.0", features = ["rt", "macros"] }
