[package]
name = "pros-simulator-server"
version = "0.1.0"
edition = "2021"
description = "Line-delimited JSON server for pros-simulator"
license = "MIT"
authors = ["doinkythederp <doinkythederp@icloud.com>", "Pros-rs Contributors"]
repository = "https://github.com/pros-rs/pros-simulator"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.4", features = ["derive"] }
jsonl = "4.0"
pros-simulator = { version = "^0.2.1", path = "../pros-simulator", default-features = false }
pros-simulator-interface = { version = "0.2", path = "../pros-simulator-interface" }
tokio = { version = "1.34", features = ["rt", "macros"] }
