[package]
name = "pros-simulator-server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.4", features = ["derive"] }
jsonl = "4.0"
pros-simulator = { version = "^0.2.1", path = "../pros-simulator", default-features = false }
pros-simulator-interface = { version = "0.2", path = "../pros-simulator-interface" }
tokio = { version = "1.34", features = ["rt", "macros"] }
