name: Release

permissions:
    contents: write

on:
    release:
        types: [created]
    workflow_dispatch:

jobs:
    upload-assets:
        strategy:
            matrix:
                include:
                    - target: aarch64-apple-darwin
                      os: macos-latest
                    - target: x86_64-unknown-linux-gnu
                      os: ubuntu-latest
                    - target: x86_64-apple-darwin
                      os: macos-latest
                    - target: x86_64-pc-windows-msvc
                      os: windows-latest
        runs-on: ${{ matrix.os }}
        steps:
            - uses: actions/checkout@v4
            - uses: actions-rs/toolchain@v1
              with:
                  toolchain: nightly
                  components: clippy
                  override: true
            - uses: doinkythederp/upload-rust-binary-action@main
              with:
                  bin: pros-simulator-server
                  target: ${{ matrix.target }}
                  token: ${{ secrets.GITHUB_TOKEN }}
                  tar: all
                  checksum: sha256
                  codesign: "-"
                  dry-run: ${{ !github.event.release }}
